// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0

package db

import (
	"time"
)

type Car struct {
	ID        int64     `json:"id"`
	ModelName string    `json:"model_name"`
	Equipment string    `json:"equipment"`
	Color     string    `json:"color"`
	Country   string    `json:"country"`
	Price     int64     `json:"price"`
	Valid     string    `json:"valid"`
	CreatedAt time.Time `json:"created_at"`
}

type Client struct {
	ID          int64  `json:"id"`
	Name        string `json:"name"`
	Country     string `json:"country"`
	PhoneNumber string `json:"phone_number"`
}

type Magazine struct {
	ID      int64  `json:"id"`
	Address string `json:"address"`
}

type Manager struct {
	ID   int64  `json:"id"`
	Name string `json:"name"`
	Town string `json:"town"`
}

type Order struct {
	ID            int64     `json:"id"`
	Car           int64     `json:"car"`
	Client        int64     `json:"client"`
	Manager       int64     `json:"manager"`
	Magazine      int64     `json:"magazine"`
	DeliveryTime  int32     `json:"delivery_time"`
	CarPrice      int64     `json:"car_price"`
	DeliveryPrice int64     `json:"delivery_price"`
	Tax           int64     `json:"tax"`
	TotalPrice    int64     `json:"total_price"`
	CreatedAt     time.Time `json:"created_at"`
}
