// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0

package db

import (
	"context"
)

type Querier interface {
	CreateClient(ctx context.Context, arg CreateClientParams) (Client, error)
	CreateMagazine(ctx context.Context, address string) (Magazine, error)
	CreateManager(ctx context.Context, arg CreateManagerParams) (Manager, error)
	GetClient(ctx context.Context, id int64) (Client, error)
	GetMagazine(ctx context.Context, id int64) (Magazine, error)
	GetManager(ctx context.Context, id int64) (Manager, error)
	ListClients(ctx context.Context, arg ListClientsParams) ([]Client, error)
	ListMagazines(ctx context.Context, arg ListMagazinesParams) ([]Magazine, error)
	ListManagers(ctx context.Context, arg ListManagersParams) ([]Manager, error)
	UpdateClient(ctx context.Context, arg UpdateClientParams) (Client, error)
	UpdateMagazine(ctx context.Context, arg UpdateMagazineParams) (Magazine, error)
	UpdateManager(ctx context.Context, arg UpdateManagerParams) (Manager, error)
}

var _ Querier = (*Queries)(nil)
